stages:
  - pre-test
  - test
  - build

build-test-image:
  stage: pre-test
  script:
    - cd ci/
    - docker build -f Dockerfile.tests -t $CI_REGISTRY_IMAGE/test-env:$CI_COMMIT_REF_SLUG .
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker push $CI_REGISTRY_IMAGE/test-env:$CI_COMMIT_REF_SLUG
  tags:
    - docker

test:
  image: $CI_REGISTRY_IMAGE/test-env:$CI_COMMIT_REF_SLUG
  stage: test
  cache:
    key: $CI_JOB_NAME-$CI_COMMIT_REF_SLUG
    paths:
      - pip-cache/
  script:
    - ./ci/run-tests.sh
  tags:
    - docker

build docker image:
  stage: build
  script:
    - docker login -u $QUAY_USER -p $QUAY_PASSWORD quay.io
    - ./ci/build-image.sh
  tags:
    - docker
