stages:
  - test

test:
  image: ubuntu:xenial
  stage: test
  script:
    - DEBIAN_FRONTEND=noninteractive apt -y update
    - DEBIAN_FRONTEND=noninteractive apt -y install python-dev python3-dev tox gcc libxml2-dev libxslt1-dev zlib1g-dev libpq-dev
    - tox
  tags:
    - docker
