image: ubuntu:xenial

pipelines:
  default:
    - step:
        script:
          - DEBIAN_FRONTEND=noninteractive apt -y update
          - DEBIAN_FRONTEND=noninteractive apt -y install python-all-dev tox gcc libxml2-dev libxslt1-dev zlib1g-dev
          - tox
